site:
  title: Bíblia modelo
  start_page: bible::index.adoc

antora:
  extensions:
    - require: ./antora/extensions/bible-navigation.cjs

content:
  sources:
    - url: .
      branches: HEAD

asciidoc:
  attributes:
    page-pagination: ''

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./antora/supplemental-ui

output:
  clean: true
  dir: ./build/site
